### ISSUE TITLE
Bug fix please

### ISSUE THREAD

**Issue by mKar01** [Lomank123/shared-music#11]
Фронтендер говноед
Получается можно ебануть ник 150 символов. 
Итог еще и бекендер бля говноед.
Ебать еще пароли русские можно писать.
Итак, мы имеем код хуйни с двумя бездарями в коллекции.
Спасибо за внимание. 

![unknown](https://user-images.githubusercontent.com/103125375/173854463-f713f597-67c5-4415-8401-b383c7dc2c6e.png)

**Comment by erikgab01** [comment]
панимаю
